spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl_auto: create # 로컬 환경
        dialect: 'org.hibernate.dialect.MySQL5Dialect'
    generate-ddl: true  # 로컬 환경
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:~/test"
    username: sa
    password:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: H2_DB
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: "spring:session"