server:
  port: 8080

spring.profiles.include: db

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl_auto: none # 로컬 환경
        dialect: 'org.hibernate.dialect.MySQL5Dialect'
    generate-ddl: false  # 로컬 환경
  freemarker:
    template-loader-path: 'classpath:/templates'
    suffix: .ftl
  h2:
    console:
      enabled: true
      path: /h2-console
  redis:
    host: 'yh-toy-redis-2.8vqaql.ng.0001.apn2.cache.amazonaws.com'
    port: 6379
  session:
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: "spring:session"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://yh-toy-database-2.cluster-cki3kdutd3oc.ap-northeast-2.rds.amazonaws.com:3306/yh_woowaton?characterEncoding=utf8
    username: admin
    password: tlzmflt1018!